apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/operator-type: non-standalone
  name: openstack-ansibleee-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: OpenStackAnsibleEE is the Schema for the openstackansibleees API
      displayName: OpenStack Ansible EE
      kind: OpenStackAnsibleEE
      name: openstackansibleees.ansibleee.openstack.org
      specDescriptors:
      - description: BackoffLimit allows to define the maximum number of retried executions
          (defaults to 6).
        displayName: Backoff Limit
        path: backoffLimit
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:number
      - description: 'RestartPolicy is the policy applied to the Job on whether it
          needs to restart the Pod. It can be "OnFailure" or "Never". RestartPolicy
          default: Never'
        displayName: Restart Policy
        path: restartPolicy
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:select:OnFailure
        - urn:alm:descriptor:com.tectonic.ui:select:Never
      - description: any_errors_fatal defaults to true
        displayName: Any Errors Fatal
        path: roles.any_errors_fatal
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - description: become defaults to false
        displayName: Become
        path: roles.become
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - description: gather_facts defaults to false
        displayName: Gather Facts
        path: roles.gather_facts
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      statusDescriptors:
      - description: Conditions
        displayName: Conditions
        path: conditions
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes.conditions
      version: v1alpha1
  description: The OpenStack Ansible Execution Environment Operator
  displayName: OpenStackAnsibleEE
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ansible
  - execution
  links:
  - name: OpenStack Ansible EE Operator
    url: https://openstack-k8s-operators.github.io/openstack-ansibleee-operator
  maintainers:
  - email: jlarriba@redhat.com
    name: Juan Larriba
  maturity: alpha
  provider:
    name: jlarriba
  version: 0.0.0
